= CXF Codegen image:https://github.com/ciscoo/cxf-codegen-gradle/workflows/Build/badge.svg?branch=master["Build Status", link="https://github.com/ciscoo/cxf-codegen-gradle/actions?query=workflow%3ABuild"]

CXF Codegen is a Gradle plugin port of the
https://cxf.apache.org/docs/maven-cxf-codegen-plugin-wsdl-to-java.html[CXF Codegen Maven plugin].

== Getting Started

The plugin is https://plugins.gradle.org/[published to Gradle's plugin portal] and can be applied
using the https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block[plugins DSL] block:

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
plugins {
    id "io.mateo.cxf-codegen" version "1.0.0-rc.3"
}
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
plugins {
    id("io.mateo.cxf-codegen") version "1.0.0-rc.3"
}
----

++++
</details>
++++

== Documentation

* https://ciscoo.github.io/cxf-codegen-gradle/docs/1.0.0-rc.3/user-guide/[User Guide]
* https://ciscoo.github.io/cxf-codegen-gradle/docs/1.0.0-rc.3/api/index.html[Javadoc]
* https://github.com/ciscoo/cxf-codegen-gradle/blob/master/CHANGELOG.adoc[Changelog]

== Snapshots

Snapshots of the next development version are published to the Sonatype OSSRH snapshot repository.

Snapshots are published for every commit to the `master` branch. Documentation for snapshots can be found https://ciscoo.github.io/cxf-codegen-gradle/docs/snapshot/user-guide/[here].

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
// build.gradle
plugins {
    id "io.mateo.cxf-codegen" version "1.0.0-SNAPSHOT"
}

// settings.gradle
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            url = uri("https://oss.sonatype.org/content/repositories/snapshots")
            mavenContent {
                snapshotsOnly()
            }
        }
    }
}
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
// build.gradle.kts

plugins {
    id("io.mateo.cxf-codegen") version "1.0.0-SNAPSHOT"
}

// settings.gradle.kts
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            url = uri("https://oss.sonatype.org/content/repositories/snapshots")
            mavenContent {
                snapshotsOnly()
            }
        }
    }
}
----

++++
</details>
++++

== Building from Source

You will need https://openjdk.java.net/projects/jdk/11/[JDK 11] to build CXF Codegen.

TIP: A compatible JDK will automatically be downloaded by Gradle if you do not have one.
See https://docs.gradle.org/current/userguide/toolchains.html[Toolchains for JVM projects] for more details.

The plugin can be built and published to your local Maven cache using the
https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle Wrapper].

[source,bash]
----
./gradlew :cxf-codegen-gradle:publishToMavenLocal
----

This will build and publish it to your local Maven cache. It won't run any of
the tests. If you want to build everything, use the `build` task:

[source,bash]
----
./gradlew build
----
