name: Prepare Gradle
description: Prepares Gradle for a GitHub Action.
inputs:
  java-version:
    description: The Java version to install.
    required: false
    default: "17"
  java-distribution:
    description: The Java distribution to install.
    required: false
    default: temurin
  java-toolchain:
    description: Whether a Java toolchain should be used.
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-java
      id: setup-java
      with:
        java-version: ${{ inputs.java-version }}
        java-distribution: ${{ inputs.java-distribution }}
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4
      with:
        allow-snapshot-wrappers: true
    - name: Set up Toolchain
      if: ${{ inputs.java-toolchain == 'true' }}
      shell: bash
      run: | # zizmor: ignore[github-env]
        echo "org.gradle.java.installations.auto-download=false" >> $HOME/.gradle/gradle.properties
        echo "JDK$JAVA_VERSION=$JAVA_HOME" >> $GITHUB_ENV
        echo $JAVA_HOME
      env:
        JAVA_VERSION: ${{ inputs.java-version }}
    - name: Display Java Toolchain Information
      shell: bash
      run: ./gradlew -q javaToolchains
