[[generating-java-sources]]
= Generating Java Sources
include::attributes.adoc[]

To generate Java sources from a WSDL, define task of type `{wsdl2java-task-type}` and configure the `toolOptions`. Note that the task is a subclass of `{javaexec-task}`.

.Incremental Build
****
The `{javaexec-task}` supports up-to-date checks (aka incremental build). As mentioned above, `{wsdl2java-task-type}` is a subclass of `{javaexec-task}` and as a result, also supports up-to-date checks.

However, depending on how your WSDLs are structured, you may encounter scenarios where tasks are out-of-date.
****

Additionally, when defining a task:

. For each task, the generated Java source (the task output) is added to the {main-source-sets}[`main` source sets].
.. This can be disabled when creating the task via `addToMainSourceSet.set(false)`
. All `{wsdl2java-task-type}` task types are aggregated to a single task named `wsdl2java`.

[[minimal-usage]]
== Minimal Usage

The minimum requirement for generating Java is a single WSDL file.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/minimal-task-usage.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/minimal-task-usage.gradle.kts[tags=code]
----

++++
</details>
++++

++++
</details>
++++

<1> Creates a task named `example` of type `{wsdl2java-task-type}`.
<2> Use the `toolOptions` to configure all available options for code generation.
<3> Configure the WSDL to use for code generation.
<4> Configure a custom locale. +
Remember that `{wsdl2java-task-type}` is a subclass of `{javaexec-task}`. All configurations you can do to `{javaexec-task}` can be done here as well.

TIP: The WSDL property is annotated with https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/InputFile.html[`@InputFile`] therefore any changes to the WSDL will cause the task to be out-of-date. If your WSDL imports a schema (XSD) or something else, consider adding that file to the
task inputs as well so that it can be considered during Gradle's https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks[up-to-date checks].

[[options-usage]]
== Options

There are quite a few options that can be specified that alter the generated Java. These are identical to ones
offered by the {cxf-codegen-maven-plugin}[Maven plugin].

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/tool-options.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/tool-options.gradle.kts[tags=code]
----

++++
</details>
++++

<1> Change the directory the generated code files are written to.
<2> Adds the `@Generated` annotation to classes.
<3> Package names to use for the generated code.
<4> Specifies subsequently generated Java class methods to allow for client-side asynchronous calls, similar to `enableAsyncMapping` in a JAX-WS binding file.

There are more options available than what is shown above. View the method summary section in the Javadoc
for `{wsdl-option}` for more details.

[[default-options]]
== Default Options

You may want to configure options that apply to all tasks. This is easily accomplished using native Gradle functionality.

First define some tasks:

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/default-tool-options.gradle[tags=primary]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/default-tool-options.gradle.kts[tags=primary]
----

++++
</details>
++++

Then configure each one using the {configure-each}[`configureEach`] method on the container:

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/default-tool-options.gradle[tags=secondary]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/default-tool-options.gradle.kts[tags=secondary]
----

++++
</details>
++++

[[java-9]]
== Java 9+

If you are using Java 9+, you can use the `cxfCodegen` configuration to add back the Java EE modules that were deprecated
in Java 9 and eventually removed in Java 11. Refer to https://openjdk.java.net/jeps/320[JEP 320] for more details.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/java-nine.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/java-nine.gradle.kts[tags=code]
----

++++
</details>
++++

<1> Replacement for `javax.xml.ws.Service`
<2> Replacement for `javax.annotation.Resource`

The above is just an example. Depending on your usage, there may be more dependencies required.

[[jakarta]]
== Jakarta

It is possible to generate Java using the `jakarta` namespace instead of `javax`. In order to do so, you must use the latest snapshots of Apache CXF along with Jakarta specific artifacts.

CAUTION: Jakarta support will be generally available in the next major release of Apache CXF.
Using Jakarta as part of the Java code generation should be done so with caution. See
https://issues.apache.org/jira/browse/CXF-8371[CXF-8371] for more details.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/jakarta.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/jakarta.gradle.kts[tags=code]
----

++++
</details>
++++

<1> Define repository for Apache CXF snapshots; filter only for CXF artifacts.
<2> Import/Use the 4.0.0 platform (BOM) for all CXF artifacts in the `cxfCodegen` classpath.
<3> Use Jakarta specific artifacts that use the `jakarta` namespace.

The above is just an example. Depending on your usage, there may be more dependencies or configuration required.

[[logging]]
== Logging

Without any additional configuration, when executing any of the created tasks, the following lines will be printed to the console:

[source,log]
----
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
----

To enable logging for Apache CXF, include a SLF4J binding and logging framework. A Logback example is shown below.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/logging-task.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/logging-task.gradle.kts[tags=code]
----

++++
</details>
++++

With the above, you should now start to see a plethora of logs as shown below.

[source,log]
----
22:14:05.833 [main] DEBUG org.apache.cxf.common.logging.LogUtils - Using org.apache.cxf.common.logging.Slf4jLogger for logging.
22:14:05.967 [main] DEBUG org.apache.cxf.tools.wsdlto.core.PluginLoader - Loading plugin jar:file:~/.gradle/caches/modules-2/files-2.1/org.apache.cxf/cxf-tools-wsdlto-databinding-jaxb/3.4.0/.../cxf-tools-wsdlto-databinding-jaxb-3.4.0.jar!/META-INF/tools-plugin.xml
22:14:06.043 [main] DEBUG org.apache.cxf.tools.wsdlto.core.PluginLoader - Found 1 databindings in <jaxb> plugin.
22:14:06.043 [main] DEBUG org.apache.cxf.tools.wsdlto.core.PluginLoader - Loading <jaxb> databinding from <jaxb> plugin.
22:14:06.043 [main] DEBUG org.apache.cxf.tools.wsdlto.core.PluginLoader - Loading plugin jar:file:~/.gradle/caches/modules-2/files-2.1/org.apache.cxf/cxf-tools-wsdlto-frontend-jaxws/3.4.0/.../cxf-tools-wsdlto-frontend-jaxws-3.4.0.jar!/META-INF/tools-plugin.xml

---- snip

22:14:06.043 [main] DEBUG org.apache.velocity - Initializing Velocity, Calling init()...
22:14:06.043 [main] DEBUG org.apache.velocity - Starting Apache Velocity v2.2
22:14:06.043 [main] DEBUG org.apache.velocity - Default Properties resource: org/apache/velocity/runtime/defaults/velocity.properties
----

[[disable-logs]]
=== Disable Logs

Logs from Apache CXF can be disabled by specifying a `null` logger for each `{wsdl2java-task}` task type as JVM argument.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/disable-task-logs.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/disable-task-logs.gradle.kts[tags=code]
----

++++
</details>
++++

Logs from Apache Velocity unfortunately cannot be disabled. However, you can specify a log configuration
that essentially overrides all logging levels. For example, an empty Logback configuration will silence all logs:

.logback.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
</configuration>
----

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/disable-all-task-logs.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/disable-all-task-logs.gradle.kts[tags=code]
----

++++
</details>
++++
