[[generating-java-sources]]
= Generating Java Sources
include::attributes.adoc[]

The {object-container}[`wsdl2java`] container can be used to define WSDL sources to generate Java sources.

For each source added to the container a corresponding task will also be created. The created task is of type
`{wsdl2java-task}` and is a subclass of `{javaexec-task}`. There is nothing special about the `{wsdl2java-task}` type,
it primarily a marker type with no additional functionality.

.Incremental Build
****
The `{javaexec-task}` supports up-to-date checks (aka incremental build). As mentioned above, `{wsdl2java-task}` is a subclass of `{javaexec-task}` and as a result, `{javaexec-task}` also supports up-to-date checks.

However, depending on how your WSDLs are structured, you may run into scenarios where `wsdl2java*` tasks are out-of-date.
****

For each WSDL source, the generated Java source is added to the {main-source-sets}[`main` source sets].

All `{wsdl2java-task}` task types are aggregated to a single task named `wsdl2java`.

[[minimal-usage]]
== Minimal Usage

The minimum requirement for generating Java is a single WSDL file.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/minimal-usage.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/minimal-usage.gradle.kts[tags=code]
----

++++
</details>
++++

With the above configuration, the plugin will create a task named `wsdl2javaExample` and output to `build/generated-sources/`.

[[options-usage]]
== Options

There are quite a few options that can be specified that alter the generated Java. These are identical to ones
offered by the {cxf-codegen-maven-plugin}[Maven plugin].

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/options.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/options.gradle.kts[tags=code]
----

++++
</details>
++++

<1> Change the directory the generated code files are written to.
<2> Adds the `@Generated` annotation to classes.
<3> Package names to use for the generated code.
<4> Specifies subsequently generated Java class methods to allow for client-side asynchronous calls, similar to `enableAsyncMapping` in a JAX-WS binding file.

There are more options available than what is shown above. View the method summary section in the Javadoc
for `{wsdl-option}` for more details.

[[default-options]]
== Default Options

You may want to configure options that apply to all WSDL sources. This is easily accomplished using native Gradle functionality.

First define some WSDL sources:

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/default-options.gradle[tags=primary]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/default-options.gradle.kts[tags=primary]
----

++++
</details>
++++

Then configure each one using the {configure-each}[`configureEach`] method on the container:

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/default-options.gradle[tags=secondary]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/default-options.gradle.kts[tags=secondary]
----

++++
</details>
++++

[[java-9]]
== Java 9+

If you are using Java 9+, you can use the `cxfCodegen` configuration to add back the Java EE modules that were deprecated
in Java 9 and eventually removed in Java 11. Refer to https://openjdk.java.net/jeps/320[JEP 320] for more details.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/java-nine.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/java-nine.gradle.kts[tags=code]
----

++++
</details>
++++

<1> Replacement for `javax.xml.ws.Service`
<2> Replacement for `javax.annotation.Resource`

The above is just an example. Depending on your usage, there may be more dependencies required.

[[logging]]
== Logging

Without any additional configuration, when executing any `wsdl2java` tasks, the following lines will be printed to the console:

[source,log]
----
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
----

To enable logging for Apache CXF, include a SLF4J binding and logging framework. A Logback example is shown below.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/logging.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/logging.gradle.kts[tags=code]
----

++++
</details>
++++

With the above, you should now start to see a plethora of logs as shown below.

[source,log]
----
22:14:05.833 [main] DEBUG org.apache.cxf.common.logging.LogUtils - Using org.apache.cxf.common.logging.Slf4jLogger for logging.
22:14:05.967 [main] DEBUG org.apache.cxf.tools.wsdlto.core.PluginLoader - Loading plugin jar:file:~/.gradle/caches/modules-2/files-2.1/org.apache.cxf/cxf-tools-wsdlto-databinding-jaxb/3.4.0/.../cxf-tools-wsdlto-databinding-jaxb-3.4.0.jar!/META-INF/tools-plugin.xml
22:14:06.043 [main] DEBUG org.apache.cxf.tools.wsdlto.core.PluginLoader - Found 1 databindings in <jaxb> plugin.
22:14:06.043 [main] DEBUG org.apache.cxf.tools.wsdlto.core.PluginLoader - Loading <jaxb> databinding from <jaxb> plugin.
22:14:06.043 [main] DEBUG org.apache.cxf.tools.wsdlto.core.PluginLoader - Loading plugin jar:file:~/.gradle/caches/modules-2/files-2.1/org.apache.cxf/cxf-tools-wsdlto-frontend-jaxws/3.4.0/.../cxf-tools-wsdlto-frontend-jaxws-3.4.0.jar!/META-INF/tools-plugin.xml

---- snip

22:14:06.043 [main] DEBUG org.apache.velocity - Initializing Velocity, Calling init()...
22:14:06.043 [main] DEBUG org.apache.velocity - Starting Apache Velocity v2.2
22:14:06.043 [main] DEBUG org.apache.velocity - Default Properties resource: org/apache/velocity/runtime/defaults/velocity.properties
----

[[disable-logs]]
=== Disable Logs

Logs from Apache CXF can be disabled by specifying a `null` logger for each `{wsdl2java-task}` task type as JVM argument.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/disable-logs.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/disable-logs.gradle.kts[tags=code]
----

++++
</details>
++++

Logs from Apache Velocity unfortunately cannot be disabled. However, you can specify a log configuration
that essentially overrides all logging levels. For example, an empty Logback configuration will silence all logs:

.logback.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
</configuration>
----

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/disable-all-logs.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/disable-all-logs.gradle.kts[tags=code]
----

++++
</details>
++++
