[[generating-java-sources]]
= Generating Java Sources
include::attributes.adoc[]

To generate Java sources from a WSDL, define task of type `{wsdl2java-task-type}` and configure the `toolOptions`. Note that the task is a subclass of `{javaexec-task}`.

.Incremental Build
****
The `{javaexec-task}` supports up-to-date checks (aka incremental build). As mentioned above, `{wsdl2java-task-type}` is a subclass of `{javaexec-task}` and as a result, also supports up-to-date checks.

However, depending on how your WSDLs are structured, you may encounter scenarios where tasks are out-of-date.
****

Additionally, when defining a task:

. For each task, the generated Java source (the task output) is added to the {main-source-sets}[`main` source sets].
.. This can be disabled when creating the task by using `addToMainSourceSet.set(false)`
. All `{wsdl2java-task-type}` task types are aggregated to a single task named `wsdl2java`.

[[minimal-usage]]
== Minimal Usage

The minimum requirement for generating Java is a single WSDL which can either be a path to a file or URL. A file example is shown below.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/minimal-task-usage.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/minimal-task-usage.gradle.kts[tags=code]
----

++++
</details>
++++

++++
</details>
++++

<1> Creates a task named `example` of type `{wsdl2java-task-type}`.
<2> Use the `toolOptions` to configure all available options for code generation.
<3> Configure the WSDL to use for code generation. The value can be a path to some location on a filesystem or a URL to a remote location.
<4> Configure a custom locale. +
Remember that `{wsdl2java-task-type}` is a subclass of `{javaexec-task}`. All configurations you can do to `{javaexec-task}` can be done here as well.

TIP: For local files, if your WSDL imports a schema (XSD) or something else, consider adding that file to the
task inputs as well so that it can be considered during Gradle's https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks[up-to-date checks].

[[options-usage]]
== Options

There are quite a few options that can be specified that alter the generated Java. These are identical to ones
offered by the {cxf-codegen-maven-plugin}[Maven plugin].

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/tool-options.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/tool-options.gradle.kts[tags=code]
----

++++
</details>
++++

<1> Change the directory the generated code files are written to.
<2> Adds the `@Generated` annotation to classes.
<3> Package names to use for the generated code.
<4> Specifies subsequently generated Java class methods to allow for client-side asynchronous calls, similar to `enableAsyncMapping` in a JAX-WS binding file.

There are more options available than what is shown above. View the method summary section in the Javadoc
for `{wsdl-option}` for more details.

[[default-options]]
== Default Options

You may want to configure options that apply to all tasks. This is easily accomplished using native Gradle functionality.

First define some tasks:

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/default-tool-options.gradle[tags=primary]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/default-tool-options.gradle.kts[tags=primary]
----

++++
</details>
++++

Then configure each one using the {configure-each}[`configureEach`] method on the container:

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/default-tool-options.gradle[tags=secondary]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/default-tool-options.gradle.kts[tags=secondary]
----

++++
</details>
++++

[[logging]]
== Logging

Without any additional configuration, when executing any of the created tasks, the following lines will be printed to the console:

[source,log]
----
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
----

Apache CXF uses SLF4J for logging. To enable logging for Apache CXF, include a SLF4J binding and logging framework. A
Logback example is shown below.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/logging-task.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/logging-task.gradle.kts[tags=code]
----

++++
</details>
++++

With the above, you will see some logs from Apache Velocity:

[source,log]
----
11:48:25.024 [main] DEBUG org.apache.velocity -- Initializing Velocity, Calling init()...
11:48:25.025 [main] DEBUG org.apache.velocity -- Starting Apache Velocity v2.3
11:48:25.026 [main] DEBUG org.apache.velocity -- Default Properties resource: org/apache/velocity/runtime/defaults/velocity.properties
----

[[verbose-logs]]
=== Verbose Logs

To see logs from Apache CXF, configure the logger for the specific task you want logs for.

NOTE: The example below configures logging for **all** `{wsdl2java-task}` tasks.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/verbose-logging.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/verbose-logging.gradle.kts[tags=code]
----

++++
</details>
++++

With the above configuration, you will see logs from Apache CXF:

[source,logs]
----
11:00:38.266 [main] DEBUG org.apache.cxf.common.logging.LogUtils -- Using org.apache.cxf.common.logging.Slf4jLogger for logging.
11:00:38.319 [main] DEBUG org.apache.cxf.tools.wsdlto.core.PluginLoader -- Loading plugin jar:file:~/.gradle/caches/modules-2/files-2.1/org.apache.cxf/cxf-tools-wsdlto-databinding-jaxb/4.0.0/5876acee034617f4f6ed756105fe9a0dc50a750c/cxf-tools-wsdlto-databinding-jaxb-4.0.0.jar!/META-INF/tools-plugin.xml
11:00:38.349 [main] DEBUG org.apache.cxf.tools.wsdlto.core.PluginLoader -- Found 1 databindings in <jaxb> plugin.
11:00:38.349 [main] DEBUG org.apache.cxf.tools.wsdlto.core.PluginLoader -- Loading <jaxb> databinding from <jaxb> plugin.
11:00:38.349 [main] DEBUG org.apache.cxf.tools.wsdlto.core.PluginLoader -- Loading plugin jar:file:~/.gradle/caches/modules-2/files-2.1/org.apache.cxf/cxf-tools-wsdlto-frontend-jaxws/4.0.0/762d4f960e3e8778af050a271218785567bc29e1/cxf-tools-wsdlto-frontend-jaxws-4.0.0.jar!/META-INF/tools-plugin.xml

...and so on
----

[[disable-logs]]
=== Disable Logs

Logs from Apache CXF can be disabled by in two ways:

. By not specifying a logger at all -- same as never enabling.
. By explicitly specifying a `null` logger as shown below.

NOTE: The example below specifies a `null` logger _**all**_ `{wsdl2java-task}` task type as JVM argument.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/disable-task-logs.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/disable-task-logs.gradle.kts[tags=code]
----

++++
</details>
++++

The Apache Velocity initialization logs unfortunately cannot be disabled. However, you can specify a log configuration
that essentially overrides all logging levels. For example, an empty Logback configuration will silence all logs:

.logback.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
</configuration>
----

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/generating-java/disable-all-task-logs.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/generating-java/disable-all-task-logs.gradle.kts[tags=code]
----

++++
</details>
++++
