[[overview]]
= Overview
include::attributes.adoc[]

The goal of this document is to provide reference documentation for developers utilizing the CXF Codegen Gradle plugin.

[[what-is-cxf-codegen-gradle]]
== What is CXF Codegen

CXF Codegen is a Gradle plugin port of the {cxf-codegen-maven-plugin}[Maven plugin].
The Gradle plugin offers an API similar to the one offered by the Maven plugin.
The API is not a 1:1 port and leans heavily on Gradle idioms and conventions.

[[getting-started]]
== Getting Started

To get started with the plugin it needs to be applied to your project.

The plugin is https://plugins.gradle.org/plugin/io.mateo.cxf-codegen[published to Gradle's plugin portal] and can be applied
using the https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block[plugins DSL] block:

++++
<details open>
<summary>Kotlin</summary>
++++

[source,kotlin,subs="verbatim,attributes"]
----
include::../gradle/overview/plugin-application.gradle.kts[]
----

++++
</details>
++++

++++
<details>
<summary>Groovy</summary>
++++

[source,groovy,subs="verbatim,attributes"]
----
include::../gradle/overview/plugin-application.gradle[]
----

++++
</details>
++++

[[supported-gradle-versions]]
== Supported Gradle Versions

The CXF Codegen Gradle plugin supports the following Gradle versions:

[cols="1"]
|===
| Gradle 8

a|
- 8.4
- 8.5
- {current-gradle-version}
|===

The plugin is fully tested against the above versions to ensure compatibility. View
the source of the {functional-test}[functional tests] for more details.

Gradle's {configuration-cache}[configuration cache] is supported.

WARNING: All examples are written for _and_ are tested for Gradle {current-gradle-version}.
Depending on your Gradle version, you may need to adapt the example to a syntax that is compatible
with your Gradle version.

[[support-policy]]
=== Support Policy

Only the current version and the previous minor versions at their latest patch versions are supported. For example, given
Gradle 8.3 is the current/latest release (as of 2023-08-17), the previous latest minor versions are 8.2.1 and 8.1.1.
Therefore Gradle 8.3, 8.2.1, and 8.1.1 are the only supported versions.

The Gradle team releases frequently and to keep this plugin up-to-date, a limited amount of versions will be supported.
