[[overview]]
= Overview
include::attributes.adoc[]

The goal of this document is to provide reference documentation for developers utilizing the CXF Codegen Gradle plugin.

[[what-is-cxf-codegen-gradle]]
== What is CXF Codegen

CXF Codegen is a Gradle plugin port of the {cxf-codegen-maven-plugin}[Maven plugin].
The Gradle plugin offers an API similar to the one offered by the Maven plugin.
The API is not a 1:1 port and leans heavily on Gradle idioms and conventions.

[[getting-started]]
== Getting Started

To get started with the plugin it needs to be applied to your project.

The plugin is https://plugins.gradle.org/plugin/io.mateo.cxf-codegen[published to Gradle's plugin portal] and can be applied
using the https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block[plugins DSL] block:

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy,subs="verbatim,attributes"]
----
include::../gradle/overview/plugin-application.gradle[]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin,subs="verbatim,attributes"]
----
include::../gradle/overview/plugin-application.gradle.kts[]
----

++++
</details>
++++

++++
</details>
++++

[[supported-gradle-versions]]
== Supported Gradle Versions

The CXF Codegen Gradle plugin supports the following Gradle versions:

[cols="1,1,1,1"]
|===
| Gradle 5 | Gradle 6 | Gradle 7 | Gradle 8

a|
- 5.5.1
- 5.6.4

a|
- 6.0.1
- 6.1.1
- 6.2.2
- 6.3
- 6.4.1
- 6.5.1
- 6.6.1
- 6.7.1
- 6.8.3
- 6.9.4

a|
- 7.0.2
- 7.1.1
- 7.2
- 7.3.3
- 7.4.2
- 7.5.1
- 7.6

a|
- {current-gradle-version}
|===

.Gradle Version Support
****
To keep the plugin as simple as possible, there will not be any _extensive_ version specific workarounds for older versions
of Gradle or any Gradle version for that matter. Trivial or simple workarounds are fine.

However, the recommended minimum Gradle version is Gradle 6.8, 6.9, or 7.x. This recommended minimum aligns with Spring
Boot Gradle Plugin 2.7.7, but without the strict requirement.
****

The plugin is fully tested against the above versions to ensure compatibility. View
the source of the {functional-test}[functional tests] for more details.

Gradle's {configuration-cache}[configuration cache] is supported when using Gradle 6.6 or later.

WARNING: All examples are written for _and_ are tested for Gradle {current-gradle-version}.
Depending on your Gradle version, you may need to adapt the example to a syntax that is compatible
with your Gradle version.
