[[overview]]
== Overview

The goal of this document is to provide reference documentation for developers utilizing the CXF Codegen Gradle plugin.

[[what-is-cxf-codegen-gradle]]
=== What is CXF Codegen Gradle

CXF Codegen Gradle is, as the name implies, a Gradle plugin based on the {cxf-codegen-maven-plugin}[Maven plugin].
The Gradle plugin offers an API similar to the one offered by the Maven plugin.
The API is not a 1:1 port and leans heavily on Gradle idioms and conventions.

[[supported-gradle-versions]]
=== Supported Gradle Versions

CXF Codegen Gradle supports the following Gradle versions:

- 5.5.1
- 5.6.4
- 6.0.1
- 6.1.1
- 6.2.2
- 6.3
- 6.4.1
- 6.5.1
- 6.6.1
- {current-gradle-version}

The plugin is fully tested against the above versions to ensure compatibility. View
the source of the {functional-test}[functional tests] for more details.

Gradle's {configuration-cache}[configuration cache] is supported when using Gradle 6.6 or later.

WARNING: All examples are written for Gradle {current-gradle-version}. Depending on your Gradle version, you may need
to adapt the syntax.