[[plugin-configuration]]
= Plugin Configuration
include::attributes.adoc[]

[[plugin-extension]]
== Extension

The plugin contributes a single extension to the project named `cxfCodegen`.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/plugin-configuration/extension.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/plugin-configuration/extension.gradle.kts[tags=code]
----

++++
</details>
++++

<1> Primary entry point to the plugin configuration.

For details on what is configuration options are available, view the Javadoc for `{cxf-codegen-extension}`.

[[dependency-configuration]]
== Dependency Configuration

The plugin creates a configuration named `cxfCodegen` which can be used to add additional dependencies to the classpath
for code generation.

Out-of-the-box, the following dependencies are added (v{cxf-version}):

* `org.apache.cxf:cxf-core`
* `org.apache.cxf:cxf-tools-common`
* `org.apache.cxf:cxf-tools-wsdlto-core`
* `org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb`
* `org.apache.cxf:cxf-tools-wsdlto-frontend-jaxws`
* `org.apache.cxf:cxf-tools-wsdlto-frontend-javascript`
** `org.apache.cxf:cxf-rt-frontend-simple` is excluded.

These are the same dependencies defined in the Maven plugin's https://github.com/apache/cxf/blob/cxf-{cxf-version}/maven-plugins/codegen-plugin/pom.xml#L71..L106[POM].

[[dependency-version-constraints]]
=== Managing Dependency Versions

There are two ways to manage the contributed dependencies:

. Through the contributed <<plugin-extension, extension>>.
. https://docs.gradle.org/current/userguide/core_dependency_management.html[Standard Gradle dependency management].

The extension provides a short and concise way to specify the version while using standard Gradle dependency management
offers more rich configuration options.

The extension is preferred for simplicity, but if your project requires more complex dependency management, then use
Gradle's dependency management instead.

[CAUTION]
====
You will need to ensure the version of CXF you specify is compatible with the
<<generating-java.adoc#options-usage, options>> used **and** your application's version of https://jakarta.ee/specifications/[Jakarta EE] (Java EE).

Additionally, depending on the version of you CXF you specify, you will also need to ensure you have the appropriate
dependencies for the `cxfCodegen` classpath and/or your application's classpath.

Failure to do so can result in an error during code generation and/or compilation errors.
====

==== Extension

To change the version using the extension, specify the version using the `cxfVersion` property:

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/plugin-configuration/managing-dependency-versions-extension.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/plugin-configuration/managing-dependency-versions-extension.gradle.kts[tags=code]
----

++++
</details>
++++

==== Standard Gradle Dependency Management

To change the version using Standard Gradle dependency management, a https://docs.gradle.org/current/userguide/resolution_rules.html#sec:dependency_resolve_rules[resolve rule]
can be used:

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/plugin-configuration/managing-dependency-versions.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/plugin-configuration/managing-dependency-versions.gradle.kts[tags=code]
----

++++
</details>
++++
