[[plugin-configuration]]
== Plugin Configuration

[[plugin-extension]]
=== Extension

The plugin contributes a single extension to the project named `cxfCodegen`.

[source,kotlin]
----
cxfCodegen { // <1>
    wsdl2java { // <2>

    }
}
----

<1> Primary entry point to the plugin configuration.
<2> WSDL sources container for generating Java. It is a {object-container}[`NamedDomainObjectContainer`] type.

[[dependency-configuration]]
=== Dependency Configuration

The plugin creates a configuration named `cxfCodegen` which can be used to add additional dependencies to the classpath
for code generation.

Out-of-the-box, the following dependencies are added:

* `org.apache.cxf:cxf-core`
* `org.apache.cxf:cxf-tools-common`
* `org.apache.cxf:cxf-tools-wsdlto-core`
* `org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb`
* `org.apache.cxf:cxf-tools-wsdlto-frontend-jaxws`

These are the same dependencies defined in the Maven plugin's https://github.com/apache/cxf/blob/master/maven-plugins/codegen-plugin/pom.xml[POM].

[[dependency-version-constraints]]
==== Managing Dependency Versions

Standard Gradle dependency management can be used to control the included dependency versions.

For example, a resolve rule can be used to downgrade the CXF dependencies:

CAUTION: You will need to ensure the version of CXF dependencies you specify is compatible with the
<<options-usage, options>> used. Failure to do so will result in an error during code generation.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
configurations.cxfCodegen {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.apache.cxf") {
            useVersion "3.2.0"
            because "We need a lower version."
        }
    }
}
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
configurations.cxfCodegen {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.apache.cxf") {
            useVersion("3.2.0")
            because("We need a lower version.")
        }
    }
}
----

++++
</details>
++++

[java-9]
==== Java 9+

If you are using Java 9+, you can use the `cxfCodegen` configuration to add back classes that were removed.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
dependencies {
    cxfCodegen "jakarta.xml.ws:jakarta.xml.ws-api:2.3.3" // <1>
    cxfCodegen "jakarta.annotation:jakarta.annotation-api:1.3.5" // <2>
}
----

<1> Replacement for `javax.xml.ws.Service`
<2> Replacement for `javax.annotation.Resource`

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
dependencies {
    cxfCodegen("jakarta.xml.ws:jakarta.xml.ws-api:2.3.3") // <1>
    cxfCodegen("jakarta.annotation:jakarta.annotation-api:1.3.5") // <2>
}
----

<1> Replacement for `javax.xml.ws.Service`
<2> Replacement for `javax.annotation.Resource`

++++
</details>
++++

The above is just an example. Depending on your usage, there may be more dependencies required.
