[[plugin-configuration]]
= Plugin Configuration
include::attributes.adoc[]

[[dependency-configuration]]
== Dependency Configuration

The plugin creates a configuration named `cxfCodegen` which can be used to add additional dependencies to the classpath
for code generation.

Out-of-the-box, the following dependencies are added (v3.5.4):

* `org.apache.cxf:cxf-core`
* `org.apache.cxf:cxf-tools-common`
* `org.apache.cxf:cxf-tools-wsdlto-core`
* `org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb`
* `org.apache.cxf:cxf-tools-wsdlto-frontend-jaxws`
* `org.apache.cxf:cxf-tools-wsdlto-frontend-javascript`
** `org.apache.cxf:cxf-rt-frontend-simple` is excluded.

These are the same dependencies defined in the Maven plugin's https://github.com/apache/cxf/blob/cxf-3.5.4/maven-plugins/codegen-plugin/pom.xml#L71..L106[POM].

[[dependency-version-constraints]]
=== Managing Dependency Versions

Standard Gradle dependency management can be used to control the included dependency versions.

For example, a resolve rule can be used to downgrade the CXF dependencies:

CAUTION: You will need to ensure the version of CXF dependencies you specify is compatible with the
<<generating-java.adoc#options-usage, options>> used. Failure to do so will result in an error during code generation.

++++
<details open>
<summary>Groovy</summary>
++++

[source,groovy]
----
include::../gradle/plugin-configuration/managing-dependency-versions.gradle[tags=code]
----

++++
</details>
++++

++++
<details>
<summary>Kotlin</summary>
++++

[source,kotlin]
----
include::../gradle/plugin-configuration/managing-dependency-versions.gradle.kts[tags=code]
----

++++
</details>
++++
