antora:
  extensions:
    - "@antora/lunr-extension"
site:
  title: CXF Codegen Gradle
  robots: allow
content:
  sources:
    - url: ../
      start_path: documentation
runtime:
  cache_dir:  ./build/antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  attributes:
    page-pagination: ""
    experimental: ""
    idprefix: ""
    idseparator: "-"
