name: Author Provided Issue Feedback

on:
  issue_comment:
    types:
      - created

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v8
        with:
          retries: 3
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const issueAuthorId = issue.data.user.id
            const commenterId = context.payload.comment.user.id
            // Only remove the label if the original author comments
            if (issueAuthorId !== commenterId) {
              return
            }
            const labelName = 'status: waiting-for-feedback'
            const hasRequiredLabel = issue.data.labels.filter(label => label.name === labelName).length === 1
            if (hasRequiredLabel) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: labelName
              })
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ["status: feedback-provided"]
              })
            }
