name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  build:
    name: "${{ matrix.os.name}}"
    runs-on: ${{ matrix.os.id }}
    if: ${{ github.repository == 'ciscoo/cxf-codegen-gradle' }}
    strategy:
      matrix:
        os:
          - id: ubuntu-latest
            name: Linux
          - id: windows-latest
            name: Windows
          - id: macos-latest
            name: macOS
    steps:
      - name: Prepare Windows runner
        if: ${{ runner.os == 'Windows' }}
        run: |
          git config --global core.autocrlf true
          git config --global core.longPaths true
          Stop-Service -name Docker
      - name: Check Out Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle
      - name: Run Checks
        shell: bash
        run: ./gradlew check
      - name: Run Functional Tests
        shell: bash
        run: ./gradlew functionalTest

  publish_snapshot_artifacts:
    name: Publish Snapshot Artifacts
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository == 'ciscoo/cxf-codegen-gradle' && github.ref == 'refs/heads/master'
    steps:
      - name: Check Out Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle
      - name: Publish
        run: ./gradlew publishAllPublicationsToMavenCentralSnapshotsRepository -x check
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

  update_snapshot_documentation:
    name: Update Snapshot Documentation
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository == 'ciscoo/cxf-codegen-gradle' && github.ref == 'refs/heads/master'
    steps:
      - name: Check Out Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: documentation/.nvmrc
      - name: Check Out GitHub Pages
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 1
      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle
      - name: Configure Gradle Properties
        run: |
          echo 'systemProp.org.gradle.internal.launcher.welcomeMessageEnabled=false' >> $GRADLE_USER_HOME/gradle.properties
          echo 'org.gradle.daemon=false' >> $GRADLE_USER_HOME/gradle.properties
      - name: Prepare Snapshot Documentation
        run: ./gradlew :documentation:prepareDocsForUpload
      - name: Sync Snapshot Documentation
        working-directory: gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          rsync -a --delete -v ../documentation/build/gh-pages ./docs/snapshot
          git add docs/snapshot
          git status
